version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tasky-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5179
      POSTGRES_DB: tasky
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:latest
    container_name: tasky-test-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5179
      POSTGRES_DB: tasky_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  postgres_test_data:
  redis-data:
