version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: tasky-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5179
      POSTGRES_DB: tasky
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - tasky-network
    restart: unless-stopped

networks:
  tasky-network:
    driver: bridge

volumes:
  postgres-data:
